### App-data
application: testfield-dw
version: 1
runtime: python27
api_version: 1
threadsafe: yes


### External tools
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

### Assets and scripts
handlers:
- url: /assets
  static_dir: assets
- url: /favicon\.ico
  static_files: assets/img/favicon.ico
  upload: favicon\.ico
- url: .*
  script: main.app
